Adds method that returns narrative data in the same format as Search API
kbaseapps/NarrativeService pull request #83
Opened 2021-10-07 16:54 UTC by charleshtrenholm

This creates a `get_narrative_doc` method that formats data in the same schema as a search API result. This is needed to return proper data to the UI for prior versions of a narrative as the search API does not index old versions.

2021-10-07 21:42 UTC, briehl requested changes
Pretty good! There's some stuff that's unclear though, check the comments above.

2021-10-07 21:42 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +        }
Looks like you're missing fields (from the .spec file):
* copied
* is_narratorial (would be in the workspace metadata from the `ws.get_workspace_info` call
* is_temporary (also in workspace metadata, and very likely false except for version 1. Brand new, unsaved Narratives start off as temporary)
* modified_at
* narrative_title 
* obj_id
* obj_name
* obj_type_module
* obj_type_version
* owner
* tags (I'm not actually sure what that is - maybe an unused field?)
* version

2021-10-07 21:42 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +    def _fmt_doc_permissions(self, permissions):
👍

2021-10-07 21:42 UTC, briehl commented on NarrativeService.spec
> +        count - the number of instances this cell appears within a given narrative.
Also, looking through the rest of the code, it seems `count` isn't even used?

2021-10-07 21:42 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +        meta = cell['metadata']['kbase']
It's possible (though unlikely) that there are cells without the `kbase` field in metadata. Maybe do something like `meta = cell['metadata'].get('kbase', {})`

2021-10-07 21:42 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +        meta = cell['metadata']['kbase']
Same goes for those fields below - maybe some fallback defaults if fields don't exist.

2021-10-07 21:42 UTC, briehl commented on test/NarrativeManager_test.py
> +    def test_get_narrative_doc(self):
Good start, but there's some other cases to consider testing for:
1. Badly formatted narrative UPA.
2. Narrative not found (so, properly formatted, but wrong workspace, object, etc.)
3. Object is found, but is not a Narrative.
4. User doesn't have permissions to the Narrative.

Really, most of those can just let the function return a RuntimeError or whatever it would do. But it would probably be helpful for the front end to be able to discern between them.

2021-10-07 22:06 UTC, charleshtrenholm commented on NarrativeService.spec
> +        count - the number of instances this cell appears within a given narrative.
@briehl No it does not appear to be used in the UI. My original understanding of it was execution count but looking at it again, I think it would be better to just remove that from the docs as I wasn't able to find a way to send that information and we agreed on sending just what the UI needs.

2021-10-07 22:14 UTC, charleshtrenholm commented on lib/NarrativeService/NarrativeServiceImpl.py
> +        restult = self._nm(ctx).get_narrative_doc(ws_id, params['narrative_upa'])
oof. I have about a 20% success rate at typing the word "result"

2021-10-07 22:21 UTC, charleshtrenholm commented on lib/NarrativeService/NarrativeManager.py
> +        }
I remember we discussed only returning for now what the UI actually consumes. The missing fields are not needed by the UI. I forgot to update the spec to reflect this, but would it be better to try and grab these extra fields?

2021-10-08 18:14 UTC, briehl commented on NarrativeService.spec
> +        string obj_type_version, list<string> tags.
👍

2021-10-08 18:16 UTC, briehl commented on test/workspace_mock.py
> +                raise ServerError('JSONRPCError: -32500')
Great!

2021-10-08 18:16 UTC, merged