adds revert_narrative_object method
kbaseapps/NarrativeService pull request #87
Opened 2021-11-19 19:31 UTC by charleshtrenholm

adds revert_narrative_object method, which reverts an object to a previous version, updates metadata, and waits until new version is indexed by search to return a success status

2021-11-19 23:35 UTC, briehl requested changes
Looks pretty good, but there's a couple things.

Also some tests for the new SearchClient would be nice to have.

2021-11-19 23:35 UTC, briehl commented on NarrativeService.spec
> +        One stop shop method for running all workspace methods related to reverting an object. sequentially runs
👍  good documentation!

2021-11-19 23:35 UTC, briehl commented on NarrativeService.spec
> +        One stop shop method for running all workspace methods related to reverting an object. sequentially runs
You could be more clear that the ObjectIdentity is used to revert the object to the chosen version number, though.

2021-11-19 23:35 UTC, briehl commented on kbase.yml
> +    0.5.0
👍

2021-11-19 23:35 UTC, briehl commented on lib/NarrativeService/SearchServiceClient.py
> +        data = requests.post(self.url, data=json.dumps(body), headers=headers).json()
What happens if there's an error?

2021-11-19 23:35 UTC, briehl commented on NarrativeService.spec
> +    } ObjectIdentity;
I think this is fine, but you don't have to support everything that the Workspace does. You could just simplify it and require numeric wsid, objid, and ver here (or whatever the UI bit provides, but numeric ids are best).

2021-11-19 23:35 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +        if (bool('wsid' in obj) == bool('workspace' in obj)):
Going along with the spec comment above, this could all be much simpler if you just require using numeric ids for the workspace and object.

2021-11-19 23:35 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +            raise ValueError(f"Cannot revert object {obj['wsid']}/{obj['objid']} without specifying a version to revert to")
:+1:

2021-11-19 23:35 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +                'id': obj['wsid']
If you have `workspace` in `obj` and not `wsid`, this'll fail. Also points to just allowing numerical ids. :)

2021-11-19 23:35 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +            return self._check_new_version_indexed(obj, new_version)
This is a good idea, but it'll spam really quickly without a timer attached to it, and may stack overflow as it's recursive. You might consider just running it in a loop with a 1 second timer, and maybe a minute or so timeout.

Something like:
```python
data = None
tries = 0
while data is None and tries < TRY_LIMIT:
    data = <do search>
    tries += 1
    time.sleep(1)
```

2021-11-29 22:05 UTC, briehl requested changes
Thanks for the changes. Got another minor one for you.

2021-11-29 22:05 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +                break
`break` isn't necessary here, raising an exception will break out of the routine.

2021-11-29 22:05 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +                break
Hm, actually, it might be better to just try again as long as there are still tries remaining. The connection might have just been flaky on that one attempt.

2021-11-29 22:05 UTC, briehl commented on lib/NarrativeService/NarrativeManager.py
> +                               'please try searching for new version later' % (obj['wsid'], obj['objid'], new_version))
Using "%" formatting is kinda deprecated in Python. Go for f-strings or the `.format` function instead.
https://docs.python.org/3/library/stdtypes.html#printf-style-string-formatting

2021-11-29 23:14 UTC, charleshtrenholm commented on lib/NarrativeService/NarrativeManager.py
> +                break
I had it continue to try until it exceeded a minute. Should be good now

2021-11-30 05:15 UTC, briehl approved these changes
Looks great! Thanks for the changes!

2021-11-30 05:15 UTC, merged